// Code generated by SQLBoiler 4.1.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Comments", testCommentsUpsert)

	t.Run("CommentLikes", testCommentLikesUpsert)

	t.Run("Friendships", testFriendshipsUpsert)

	t.Run("Images", testImagesUpsert)

	t.Run("ImageVariations", testImageVariationsUpsert)

	t.Run("Likes", testLikesUpsert)

	t.Run("Posts", testPostsUpsert)

	t.Run("Users", testUsersUpsert)
}
