version: "3"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - DATABASE_SSL_MODE=disable
      - POSTGRES_PASSWORD=password
    volumes:
      - ./soap.sql:/docker-entrypoint-initdb.d/soap.sql
    expose:
      - 5432
    ports:
      - 5432:5432
