// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package helpers

import (
	"context"

	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/web-ridge/gqlgen-sqlboiler-examples/issue-6-edges-connections/models"
	boilergql "github.com/web-ridge/utils-go/boilergql/v3"
)

var TablePreloadMap = map[string]map[string]boilergql.ColumnSetting{
	models.TableNames.User: {},
}

func GetUserPreloadMods(ctx context.Context) (queryMods []qm.QueryMod) {
	return boilergql.GetPreloadModsWithLevel(ctx, TablePreloadMap, models.TableNames.User, "")
}

func GetUserPreloadModsWithLevel(ctx context.Context, level string) (queryMods []qm.QueryMod) {
	return boilergql.GetPreloadModsWithLevel(ctx, TablePreloadMap, models.TableNames.User, level)
}
