version: "3"

services:
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./connections.sql:/docker-entrypoint-initdb.d/connections.sql
    ports:
      - "3390:3306"
