// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testRecipeAdditives(t *testing.T) {
	t.Parallel()

	query := RecipeAdditives()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testRecipeAdditivesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecipeAdditive{}
	if err = randomize.Struct(seed, o, recipeAdditiveDBTypes, true, recipeAdditiveColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeAdditive struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RecipeAdditives().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRecipeAdditivesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecipeAdditive{}
	if err = randomize.Struct(seed, o, recipeAdditiveDBTypes, true, recipeAdditiveColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeAdditive struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := RecipeAdditives().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RecipeAdditives().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRecipeAdditivesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecipeAdditive{}
	if err = randomize.Struct(seed, o, recipeAdditiveDBTypes, true, recipeAdditiveColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeAdditive struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RecipeAdditiveSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RecipeAdditives().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRecipeAdditivesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecipeAdditive{}
	if err = randomize.Struct(seed, o, recipeAdditiveDBTypes, true, recipeAdditiveColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeAdditive struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := RecipeAdditiveExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if RecipeAdditive exists: %s", err)
	}
	if !e {
		t.Errorf("Expected RecipeAdditiveExists to return true, but got false.")
	}
}

func testRecipeAdditivesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecipeAdditive{}
	if err = randomize.Struct(seed, o, recipeAdditiveDBTypes, true, recipeAdditiveColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeAdditive struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	recipeAdditiveFound, err := FindRecipeAdditive(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if recipeAdditiveFound == nil {
		t.Error("want a record, got nil")
	}
}

func testRecipeAdditivesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecipeAdditive{}
	if err = randomize.Struct(seed, o, recipeAdditiveDBTypes, true, recipeAdditiveColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeAdditive struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = RecipeAdditives().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testRecipeAdditivesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecipeAdditive{}
	if err = randomize.Struct(seed, o, recipeAdditiveDBTypes, true, recipeAdditiveColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeAdditive struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := RecipeAdditives().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testRecipeAdditivesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	recipeAdditiveOne := &RecipeAdditive{}
	recipeAdditiveTwo := &RecipeAdditive{}
	if err = randomize.Struct(seed, recipeAdditiveOne, recipeAdditiveDBTypes, false, recipeAdditiveColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeAdditive struct: %s", err)
	}
	if err = randomize.Struct(seed, recipeAdditiveTwo, recipeAdditiveDBTypes, false, recipeAdditiveColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeAdditive struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = recipeAdditiveOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = recipeAdditiveTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := RecipeAdditives().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testRecipeAdditivesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	recipeAdditiveOne := &RecipeAdditive{}
	recipeAdditiveTwo := &RecipeAdditive{}
	if err = randomize.Struct(seed, recipeAdditiveOne, recipeAdditiveDBTypes, false, recipeAdditiveColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeAdditive struct: %s", err)
	}
	if err = randomize.Struct(seed, recipeAdditiveTwo, recipeAdditiveDBTypes, false, recipeAdditiveColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeAdditive struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = recipeAdditiveOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = recipeAdditiveTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RecipeAdditives().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func recipeAdditiveBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *RecipeAdditive) error {
	*o = RecipeAdditive{}
	return nil
}

func recipeAdditiveAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *RecipeAdditive) error {
	*o = RecipeAdditive{}
	return nil
}

func recipeAdditiveAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *RecipeAdditive) error {
	*o = RecipeAdditive{}
	return nil
}

func recipeAdditiveBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *RecipeAdditive) error {
	*o = RecipeAdditive{}
	return nil
}

func recipeAdditiveAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *RecipeAdditive) error {
	*o = RecipeAdditive{}
	return nil
}

func recipeAdditiveBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *RecipeAdditive) error {
	*o = RecipeAdditive{}
	return nil
}

func recipeAdditiveAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *RecipeAdditive) error {
	*o = RecipeAdditive{}
	return nil
}

func recipeAdditiveBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *RecipeAdditive) error {
	*o = RecipeAdditive{}
	return nil
}

func recipeAdditiveAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *RecipeAdditive) error {
	*o = RecipeAdditive{}
	return nil
}

func testRecipeAdditivesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &RecipeAdditive{}
	o := &RecipeAdditive{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, recipeAdditiveDBTypes, false); err != nil {
		t.Errorf("Unable to randomize RecipeAdditive object: %s", err)
	}

	AddRecipeAdditiveHook(boil.BeforeInsertHook, recipeAdditiveBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	recipeAdditiveBeforeInsertHooks = []RecipeAdditiveHook{}

	AddRecipeAdditiveHook(boil.AfterInsertHook, recipeAdditiveAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	recipeAdditiveAfterInsertHooks = []RecipeAdditiveHook{}

	AddRecipeAdditiveHook(boil.AfterSelectHook, recipeAdditiveAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	recipeAdditiveAfterSelectHooks = []RecipeAdditiveHook{}

	AddRecipeAdditiveHook(boil.BeforeUpdateHook, recipeAdditiveBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	recipeAdditiveBeforeUpdateHooks = []RecipeAdditiveHook{}

	AddRecipeAdditiveHook(boil.AfterUpdateHook, recipeAdditiveAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	recipeAdditiveAfterUpdateHooks = []RecipeAdditiveHook{}

	AddRecipeAdditiveHook(boil.BeforeDeleteHook, recipeAdditiveBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	recipeAdditiveBeforeDeleteHooks = []RecipeAdditiveHook{}

	AddRecipeAdditiveHook(boil.AfterDeleteHook, recipeAdditiveAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	recipeAdditiveAfterDeleteHooks = []RecipeAdditiveHook{}

	AddRecipeAdditiveHook(boil.BeforeUpsertHook, recipeAdditiveBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	recipeAdditiveBeforeUpsertHooks = []RecipeAdditiveHook{}

	AddRecipeAdditiveHook(boil.AfterUpsertHook, recipeAdditiveAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	recipeAdditiveAfterUpsertHooks = []RecipeAdditiveHook{}
}

func testRecipeAdditivesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecipeAdditive{}
	if err = randomize.Struct(seed, o, recipeAdditiveDBTypes, true, recipeAdditiveColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeAdditive struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RecipeAdditives().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRecipeAdditivesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecipeAdditive{}
	if err = randomize.Struct(seed, o, recipeAdditiveDBTypes, true); err != nil {
		t.Errorf("Unable to randomize RecipeAdditive struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(recipeAdditiveColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := RecipeAdditives().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRecipeAdditiveToOneAdditiveUsingAdditive(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local RecipeAdditive
	var foreign Additive

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, recipeAdditiveDBTypes, false, recipeAdditiveColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeAdditive struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, additiveDBTypes, false, additiveColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Additive struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.AdditiveID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Additive().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := RecipeAdditiveSlice{&local}
	if err = local.L.LoadAdditive(ctx, tx, false, (*[]*RecipeAdditive)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Additive == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Additive = nil
	if err = local.L.LoadAdditive(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Additive == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testRecipeAdditiveToOneRecipeUsingRecipe(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local RecipeAdditive
	var foreign Recipe

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, recipeAdditiveDBTypes, false, recipeAdditiveColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeAdditive struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, recipeDBTypes, false, recipeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Recipe struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.RecipeID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Recipe().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := RecipeAdditiveSlice{&local}
	if err = local.L.LoadRecipe(ctx, tx, false, (*[]*RecipeAdditive)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Recipe == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Recipe = nil
	if err = local.L.LoadRecipe(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Recipe == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testRecipeAdditiveToOneSetOpAdditiveUsingAdditive(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a RecipeAdditive
	var b, c Additive

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, recipeAdditiveDBTypes, false, strmangle.SetComplement(recipeAdditivePrimaryKeyColumns, recipeAdditiveColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, additiveDBTypes, false, strmangle.SetComplement(additivePrimaryKeyColumns, additiveColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, additiveDBTypes, false, strmangle.SetComplement(additivePrimaryKeyColumns, additiveColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Additive{&b, &c} {
		err = a.SetAdditive(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Additive != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.RecipeAdditive != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.AdditiveID != x.ID {
			t.Error("foreign key was wrong value", a.AdditiveID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.AdditiveID))
		reflect.Indirect(reflect.ValueOf(&a.AdditiveID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.AdditiveID != x.ID {
			t.Error("foreign key was wrong value", a.AdditiveID, x.ID)
		}
	}
}
func testRecipeAdditiveToOneSetOpRecipeUsingRecipe(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a RecipeAdditive
	var b, c Recipe

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, recipeAdditiveDBTypes, false, strmangle.SetComplement(recipeAdditivePrimaryKeyColumns, recipeAdditiveColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, recipeDBTypes, false, strmangle.SetComplement(recipePrimaryKeyColumns, recipeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, recipeDBTypes, false, strmangle.SetComplement(recipePrimaryKeyColumns, recipeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Recipe{&b, &c} {
		err = a.SetRecipe(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Recipe != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.RecipeAdditives[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.RecipeID != x.ID {
			t.Error("foreign key was wrong value", a.RecipeID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.RecipeID))
		reflect.Indirect(reflect.ValueOf(&a.RecipeID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.RecipeID != x.ID {
			t.Error("foreign key was wrong value", a.RecipeID, x.ID)
		}
	}
}

func testRecipeAdditivesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecipeAdditive{}
	if err = randomize.Struct(seed, o, recipeAdditiveDBTypes, true, recipeAdditiveColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeAdditive struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRecipeAdditivesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecipeAdditive{}
	if err = randomize.Struct(seed, o, recipeAdditiveDBTypes, true, recipeAdditiveColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeAdditive struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RecipeAdditiveSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRecipeAdditivesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecipeAdditive{}
	if err = randomize.Struct(seed, o, recipeAdditiveDBTypes, true, recipeAdditiveColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeAdditive struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := RecipeAdditives().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	recipeAdditiveDBTypes = map[string]string{`ID`: `integer`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`, `DeletedAt`: `timestamp with time zone`, `Percentage`: `double precision`, `AdditiveID`: `integer`, `RecipeID`: `integer`}
	_                     = bytes.MinRead
)

func testRecipeAdditivesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(recipeAdditivePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(recipeAdditiveAllColumns) == len(recipeAdditivePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &RecipeAdditive{}
	if err = randomize.Struct(seed, o, recipeAdditiveDBTypes, true, recipeAdditiveColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeAdditive struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RecipeAdditives().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, recipeAdditiveDBTypes, true, recipeAdditivePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RecipeAdditive struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testRecipeAdditivesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(recipeAdditiveAllColumns) == len(recipeAdditivePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &RecipeAdditive{}
	if err = randomize.Struct(seed, o, recipeAdditiveDBTypes, true, recipeAdditiveColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeAdditive struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RecipeAdditives().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, recipeAdditiveDBTypes, true, recipeAdditivePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RecipeAdditive struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(recipeAdditiveAllColumns, recipeAdditivePrimaryKeyColumns) {
		fields = recipeAdditiveAllColumns
	} else {
		fields = strmangle.SetComplement(
			recipeAdditiveAllColumns,
			recipeAdditivePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := RecipeAdditiveSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testRecipeAdditivesUpsert(t *testing.T) {
	t.Parallel()

	if len(recipeAdditiveAllColumns) == len(recipeAdditivePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := RecipeAdditive{}
	if err = randomize.Struct(seed, &o, recipeAdditiveDBTypes, true); err != nil {
		t.Errorf("Unable to randomize RecipeAdditive struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert RecipeAdditive: %s", err)
	}

	count, err := RecipeAdditives().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, recipeAdditiveDBTypes, false, recipeAdditivePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RecipeAdditive struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert RecipeAdditive: %s", err)
	}

	count, err = RecipeAdditives().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
